[project]
name = "icp-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "debugpy>=1.8.20",
    "marimo>=0.19.11",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pypcd4>=1.4.3",
    "pyzmq>=27.1.0",
]
